repos:
  - repo: local
    hooks:
      - id: isort
        name: isort (from .venv)
        entry: isort
        language: system
        types: [python]
        args: ["--profile", "black"]

      - id: black
        name: black (from .venv)
        entry: black
        language: system
        types: [python]
