train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.ArgmaxCERMetric
    name: "CER_(Argmax)" # it is better to avoid spaces in names
  - _target_: src.metrics.ArgmaxWERMetric
    name: "WER_(Argmax)"
  
  - _target_: src.metrics.BeamCERMetric
    name: "CER_(Beam10)"
    beam_size: 10
  - _target_: src.metrics.BeamWERMetric
    name: "WER_(Beam10)"
    beam_size: 10