defaults:
  - model: conformer_ctc
  - writer: cometml
  - metrics: argmax_beam_10
  - datasets: example
  - dataloader: big_batch
  - transforms: pipeline_wav_spec
  - _self_

optimizer:
  _target_: torch.optim.AdamW
  lr: 3e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  max_lr: 1e-2
  pct_start: 0.1
  steps_per_epoch: ${trainer.epoch_len}
  epochs: ${trainer.n_epochs}
  anneal_strategy: cos

loss_function:
  _target_: src.loss.CTCLossWrapper

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder

trainer:
  log_step: 100
  n_epochs: 10
  epoch_len: 1000
  device_tensors: ["spectrogram", "spectrogram_length", "text_encoded", "text_encoded_length"]
  resume_from: null
  device: auto
  override: false
  monitor: "min val_WER_(Argmax)"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
