defaults:
  - model: conformer_ctc
  - metrics: argmax_beam_10
  - datasets: example # we do not want to run inference on training data
  - dataloader: big_batch
  - transforms: pipeline_wav_spec
  - _self_
inferencer:
  device_tensors: ["spectrogram", "spectrogram_length", "text_encoded", "text_encoded_length"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
  save_path: "inference_run"
  decoding: argmax
  beam_size: 10

text_encoder:
  _target_: src.text_encoder.CTCTextEncoder